language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - DOCTRINE_VERSION=2.6.*

install:
  - composer self-update
  - composer install
  - composer require doctrine/orm:${DOCTRINE_VERSION} --dev --prefer-source --update-with-dependencies

notifications:
  email: false

script:
  - make test
  - if [[ $DOCTRINE_VERSION == 2.6.* && $TRAVIS_PHP_VERSION == 7.3 ]]; then make lint; fi

sudo: false
dist: precise

cache:
  directories:
    - $COMPOSER_CACHE_DIR
