language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  
env:
  - DOCTRINE_VERSION=2.1.*
  - DOCTRINE_VERSION=2.2.*
  - DOCTRINE_VERSION=2.3.*
  - DOCTRINE_VERSION=2.4.*
  - DOCTRINE_VERSION=2.5.*

matrix:
  exclude:
  - php: 5.3
    env: DOCTRINE_VERSION=2.5.*

install:
  - composer self-update
  - composer install
  - composer require doctrine/orm:${DOCTRINE_VERSION} --dev --prefer-source --update-with-dependencies

notifications:
  email: false

script: vendor/bin/phpunit

sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
